spring:
  application:
    name: codebreaker-community
  profiles:
    active:
      - service
      - local
  datasource:
    url: "jdbc:h2:file:./db/codebreaker"
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    database-platform: "org.hibernate.dialect.H2Dialect"
  sql:
    init:
      mode: always
